Update lifecycle status
rancher/charts-build-scripts pull request #144
Opened 2024-07-26 19:09 UTC by nicholasSUSE

#### Issue:

https://github.com/rancher/ecm-distro-tools/issues/445

#### Solution:

Changing main behavior of `lifecycle-status` from creating and cloning a temporary directory structure for `rancher/charts repository` to executing all actions in the current charts repository and persisting the results to parsable `state.json` file that can be loaded by different commands.

2024-07-26 19:28 UTC, briandowns requested changes

2024-07-26 19:28 UTC, briandowns commented on pkg/lifecycle/state.go
> +package lifecycle
Remove all logging from library code please.

2024-07-26 19:28 UTC, briandowns commented on pkg/lifecycle/state.go
> +	// Read the file content
Move this comment above the operation

2024-07-26 19:28 UTC, briandowns commented on pkg/lifecycle/state.go
> +	err := s.createStateFile()
Make all calls that do a single error check inline.

2024-07-26 19:28 UTC, briandowns commented on pkg/lifecycle/state.go
> +		err = fmt.Errorf("error marshalling project to JSON: %w", err)
Are all of the errors here lacking enough context to warrant having more info added? Usually not necessary and not a standard for the lang or the repo.

2024-07-26 19:33 UTC, tashima42 approved these changes

2024-07-29 16:36 UTC, nicholasSUSE commented
@briandowns all fixes implemented.

2024-07-30 20:53 UTC, briandowns approved these changes

2024-07-30 21:04 UTC, merged