Validate release charts
rancher/charts-build-scripts pull request #149
Opened 2024-09-06 18:06 UTC by nicholasSUSE

2024-09-06 18:11 UTC, nicholasSUSE commented
@rancher/release-team
I know the linter is failing, I am on to fix the errors.

2024-09-06 21:46 UTC, nicholasSUSE commented
Ok, I started working on the code the linter pointed, and unit tests started breaking. 
I will separate some time to refactor this, for now disregard it.

2024-09-06 22:11 UTC, tashima42 requested changes

2024-09-10 16:06 UTC, nicholasSUSE commented on main.go
> +	}
I will do that in time. 
For now, I am just updating whatever I am working on.

2024-09-10 16:54 UTC, tashima42 commented on main.go
> +	}
It's fine not changing other functions now, but I really think in the same function, the same type of fatal should be used. e.g:
```diff
- logrus.Fatalf("encountered error while initializing d: %v", err)
+ fmt.Printf("encountered error while initializing d: %v", err)
+ os.Exit(1)
```

2024-09-11 18:56 UTC, nicholasSUSE commented on main.go
> +	}
@tashima42 now ready

2024-09-11 21:05 UTC, nicholasSUSE commented
Bypassing linter until refactoring of legacy code

2024-09-11 21:07 UTC, merged